### PR TITLE
Responsive layout

### LINKED ISSUE #3: Site not responsive in mobile and smaller devices
ConvertFFS website is not responsive in mobile and smaller devices. Need to work on responsiveness.

### PR DESCRIPTION
**Pull request by jayeclark**
Signed-off-by: Jay Clark <jay@jayeclark.dev>

# Description
Good morning and happy Hacktoberfest @diamondzxd ! I took a crack at resolving the responsive layout issue - let me know what you think.

# Related Issue
Fixes #3 

# Type of Contribution
- [ ] Bug fix
- [ ] Coding
- [X] Design
- [ ] Testing
- [ ] Research
- [ ] Enhancement
- [ ] Documentation
- [ ] Other :

# Checklist
- [X] I have read README.md and CONTRIBUTION.md
- [X] My Pull request is made against develop branch.
- [X] My code/design follows the style/guidelines of this project.
- [X] I have performed a self-review of my own code/design/documentation.
- [X] I have commented my code, particularly in hard-to-understand area(or gave a proper description about the design.)

## Screenshots (if applicable):

responsive

### CODE REVIEW

**Review by diamondzxd — APPROVED** [review]
Hello @jayeclark , thanks for taking your time for the awesome contribution :)

It looks really nice and I'll get it implemented to the main website shortly!

**Comment by diamondzxd** [comment]
Good Morning @jayeclark 

After some testing, I am not able to recreate that responsive behavior on my end.

Desktop GIF - https://i.ibb.co/kX0KG5Y/2021-October-21-09-54-49-PM.gif

The site looks a bit off from the original design in Desktop View.

I have mentioned the new issues which arose. Feel free to create a new Pull Request for the changes if you want.

Happy Hacktoberfest!

Before 
Before Desktop

After - 
After Desktop

Mobile Screenshot - Mobile Screenshot

**Comment by jayeclark** [comment]
@diamondzxd Hmm. I can fix the max-width on desktop issue (I had actually been debating whether to set that or not), but I can't recreate the mobile layout error so will have to poke around a little on that one.

**Comment by jayeclark** [comment]
@diamondzxd I believe this is fixed with the new pull request... I had changed some kebab-case classes at the end, to match the camelcase style of the rest of the project, but missed a couple which caused the layout to no longer adjust at the breakpoints. Lesson learned!

**Comment by diamondzxd** [comment]
Seems to have fixed now.

Thanks a lot! @jayeclark

**Pull request merged**
